// <auto-generated />
using System;
using DigitalWorkshop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalWorkshop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506010657_AddTpExtendedProperties")]
    partial class AddTpExtendedProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnologyProcessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyProcessId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.BomItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransitionId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TransitionId");

                    b.ToTable("BomItems");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NormTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("RequiredQualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnologyProcessId")
                        .HasColumnType("int");

                    b.Property<string>("WorkCenter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyProcessId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.TechnologyProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VersionHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionMajor")
                        .HasColumnType("int");

                    b.Property<int>("VersionMinor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TechnologyProcesses");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.ToolRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransitionId")
                        .HasColumnType("int");

                    b.Property<int?>("VerificationIntervalDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransitionId");

                    b.ToTable("ToolRequirements");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.Transition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxParam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MinParam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<string>("ParamUnit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("Transitions");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("DigitalWorkshop.Domain.Entities.TechnologyProcess", "TechnologyProcess")
                        .WithMany("History")
                        .HasForeignKey("TechnologyProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnologyProcess");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.BomItem", b =>
                {
                    b.HasOne("DigitalWorkshop.Domain.Entities.Transition", "Transition")
                        .WithMany("BomItems")
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transition");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.Operation", b =>
                {
                    b.HasOne("DigitalWorkshop.Domain.Entities.TechnologyProcess", "TechnologyProcess")
                        .WithMany("Operations")
                        .HasForeignKey("TechnologyProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnologyProcess");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.ToolRequirement", b =>
                {
                    b.HasOne("DigitalWorkshop.Domain.Entities.Transition", "Transition")
                        .WithMany("Tools")
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transition");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.Transition", b =>
                {
                    b.HasOne("DigitalWorkshop.Domain.Entities.Operation", "Operation")
                        .WithMany("Transitions")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.Operation", b =>
                {
                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.TechnologyProcess", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("DigitalWorkshop.Domain.Entities.Transition", b =>
                {
                    b.Navigation("BomItems");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
